elfin_left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - elfin_l_joint1
     - elfin_l_joint2
     - elfin_l_joint3
     - elfin_l_joint4
     - elfin_l_joint5
     - elfin_l_joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10

elfin_right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - elfin_r_joint1
     - elfin_r_joint2
     - elfin_r_joint3
     - elfin_r_joint4
     - elfin_r_joint5
     - elfin_r_joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10