controller_list:
  - name: fake_elfin_left_arm_controller
    joints:
      - elfin_l_joint1
      - elfin_l_joint2
      - elfin_l_joint3
      - elfin_l_joint4
      - elfin_l_joint5
      - elfin_l_joint6
  - name: fake_elfin_right_arm_controller
    joints:
      - elfin_r_joint1
      - elfin_r_joint2
      - elfin_r_joint3
      - elfin_r_joint4
      - elfin_r_joint5
      - elfin_r_joint6