# Simulation settings for using moveit_sim_controllers
# moveit_sim_hw_interface:
#   joint_model_group: elfin_left_arm
#   joint_model_group_pose: pose1
# Settings for ros_control_boilerplate control loop
# generic_hw_control_loop:
#   loop_hz: 300
#   cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - elfin_l_joint1
    - elfin_l_joint2
    - elfin_l_joint3
    - elfin_l_joint4
    - elfin_l_joint5
    - elfin_l_joint6
    - elfin_r_joint1
    - elfin_r_joint2
    - elfin_r_joint3
    - elfin_r_joint4
    - elfin_r_joint5
    - elfin_r_joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: elfin_left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - elfin_l_joint1
      - elfin_l_joint2
      - elfin_l_joint3
      - elfin_l_joint4
      - elfin_l_joint5
      - elfin_l_joint6
  - name: elfin_right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - elfin_r_joint1
      - elfin_r_joint2
      - elfin_r_joint3
      - elfin_r_joint4
      - elfin_r_joint5
      - elfin_r_joint6